In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option('display.float_format', lambda x: '{:,.3f}'.format(x) if abs(x)<0 else ('{:,.2f}'.format(x) if abs(x)<10 else ('{:,.1f}'.format(x) if abs(x)<100 else '{:,.0f}'.format(x))))

In [2]:
filepath= r"./output/"
df_budget = pd.read_csv(filepath+'table_budget_ch4.csv',index_col=0)
df_budget['Feedback factor']=None
df_budget

,CH4 burden [Tg],CH4 surface conc. [ppbv],CH4 chem loss OH [Tg/yr],CH4 chem loss other strat [Tg/yr],CH4 loss soil [Tg/yr],CH4 total loss [Tg/yr],CH4 lifetime due to OH (whole atmosphere) [yrs],Total CH4 lifetime [yrs],Feedback factor
CTRL,"4,975","1,813",674,20.7,31.1,726,7.38,6.85,None
CNTR_SSP119,"3,916","1,427",511,16.3,24.5,552,7.67,7.10,None
CNTR_SSP434,"6,104","2,223",724,25.4,38.2,787,8.43,7.75,None
CNTR_SSP585,"6,713","2,446",841,28.0,42.0,910,7.99,7.37,None

In [3]:
df_feedback = pd.read_csv(filepath+'feedback_factor_ch4.csv',index_col=0)
df_feedback

,antro01,antro1,antro10,antro100,nemo,epia,munich,usdrydep,maud,zep,maxdep,SSP119,SSP434,SSP585
OSLOCTM,1.46,1.46,1.46,1.46,1.46,1.46,1.46,1.46,1.46,1.46,1.46,1.52,1.71,1.67

In [4]:
df_budget['Feedback factor'].loc['CTRL']=df_feedback['antro01'].loc['OSLOCTM']

scen_list = ['SSP119','SSP434','SSP585']
for scen in scen_list:
    df_budget['Feedback factor'].loc['CNTR_'+scen] = df_feedback[scen].loc['OSLOCTM']
df_budget

/home/ragnhibs/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

,CH4 burden [Tg],CH4 surface conc. [ppbv],CH4 chem loss OH [Tg/yr],CH4 chem loss other strat [Tg/yr],CH4 loss soil [Tg/yr],CH4 total loss [Tg/yr],CH4 lifetime due to OH (whole atmosphere) [yrs],Total CH4 lifetime [yrs],Feedback factor
CTRL,"4,975","1,813",674,20.7,31.1,726,7.38,6.85,1.46
CNTR_SSP119,"3,916","1,427",511,16.3,24.5,552,7.67,7.10,1.52
CNTR_SSP434,"6,104","2,223",724,25.4,38.2,787,8.43,7.75,1.71
CNTR_SSP585,"6,713","2,446",841,28.0,42.0,910,7.99,7.37,1.67

In [5]:
df_budget['Perturbation lifetime'] = df_budget['Total CH4 lifetime [yrs]']* df_budget['Feedback factor']

#df_budget = df_budget.reindex(sorted_array)
df_budget

,CH4 burden [Tg],CH4 surface conc. [ppbv],CH4 chem loss OH [Tg/yr],CH4 chem loss other strat [Tg/yr],CH4 loss soil [Tg/yr],CH4 total loss [Tg/yr],CH4 lifetime due to OH (whole atmosphere) [yrs],Total CH4 lifetime [yrs],Feedback factor,Perturbation lifetime
CTRL,"4,975","1,813",674,20.7,31.1,726,7.38,6.85,1.46,10.0
CNTR_SSP119,"3,916","1,427",511,16.3,24.5,552,7.67,7.10,1.52,10.8
CNTR_SSP434,"6,104","2,223",724,25.4,38.2,787,8.43,7.75,1.71,13.3
CNTR_SSP585,"6,713","2,446",841,28.0,42.0,910,7.99,7.37,1.67,12.3

Add numbers from Prather et al 2012

df_budget.loc['Prather et al. 2012'] = np.nan
scale_frac = 5000./4932. 

df_budget.loc['Prather et al. 2012']['Total CH4 lifetime [yrs]'] = 9.1
df_budget.loc['Prather et al. 2012']['CH4 surface conc. [ppbv]'] =1795. *scale_frac
df_budget.loc['Prather et al. 2012']['CH4 burden [Tg]'] = 4932.*scale_frac
df_budget.loc['Prather et al. 2012']['CH4 total loss [Tg/yr]'] = 540.*scale_frac
df_budget.loc['Prather et al. 2012']['CH4 lifetime due to OH [yrs]'] =1./0.0895

df_budget.loc['Prather et al. 2012']['Feedback factor'] =1/(1-0.32)

print(df_budget.loc['Prather et al. 2012']['CH4 burden [Tg]']/df_budget.loc['Prather et al. 2012']['CH4 total loss [Tg/yr]']) 
df_budget

In [7]:
df_budget_diff = df_budget[['CH4 burden [Tg]','CH4 surface conc. [ppbv]','CH4 lifetime due to OH (whole atmosphere) [yrs]','Total CH4 lifetime [yrs]','Feedback factor','Perturbation lifetime']]
ssp_list = ['SSP119','SSP434','SSP585']
for ssp in ssp_list:
    df_budget_diff.loc[ssp] = df_budget_diff.loc['CNTR_'+ssp]-df_budget_diff.loc['CTRL']

df_budget_diff.loc[['CTRL','SSP119','SSP434','SSP585']]

/home/ragnhibs/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

,CH4 burden [Tg],CH4 surface conc. [ppbv],CH4 lifetime due to OH (whole atmosphere) [yrs],Total CH4 lifetime [yrs],Feedback factor,Perturbation lifetime
CTRL,"4,975","1,813",7.38,6.85,1.46,10.0
SSP119,"-1,059",-386,0.29,0.25,0.05,0.72
SSP434,"1,129",410,1.05,0.90,0.25,3.24
SSP585,"1,738",633,0.61,0.52,0.21,2.31

In [12]:
df_budget_diff_toegu = df_budget_diff.loc[['CTRL','SSP119','SSP434','SSP585']]
re_index = {'SSP119': 'diff. SSP119',
            'SSP434': 'diff. SSP434',
            'SSP585': 'diff. SSP585'}
df_budget_diff_toegu = df_budget_diff_toegu.rename(re_index)
df_budget_diff_toegu

,CH4 burden [Tg],CH4 surface conc. [ppbv],CH4 lifetime due to OH (whole atmosphere) [yrs],Total CH4 lifetime [yrs],Feedback factor,Perturbation lifetime
CTRL,"4,975","1,813",7.38,6.85,1.46,10.0
diff. SSP119,"-1,059",-386,0.29,0.25,0.05,0.72
diff. SSP434,"1,129",410,1.05,0.90,0.25,3.24
diff. SSP585,"1,738",633,0.61,0.52,0.21,2.31

In [24]:
df_budget_diff_toegu