In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.float_format', lambda x: '{:,.4f}'.format(x) if abs(x)<0 else ('{:,.2f}'.format(x) if abs(x)<10 else ('{:,.1f}'.format(x) if abs(x)<100 else '{:,.0f}'.format(x))))

In [2]:
outputpath= r"./output/"

In [3]:
df_lifetime = pd.read_csv(outputpath + 'for_lifetimetable.csv',sep=',',index_col=0)
df_lifetime

          h2_burden  h2_burden_delta  h2_loss  h2_atm_loss  h2_soil_sink_loss
CNTR            205             0.00     87.2         29.2               58.0
antro01         205             0.22     87.3         29.2               58.1
antro1          207             2.15     88.2         29.5               58.7
antro10         226             21.5     97.1         32.1               65.0
antro100        423              218      186         58.0                128
nemo            207             2.53     88.2         29.5               58.7
epia            207             1.93     88.2         29.4               58.7
munich          207             2.05     88.2         29.5               58.7
usdrydep        206             1.76     88.2         29.4               58.8
maud            207             2.56     88.2         29.5               58.7
zep             207             2.07     88.2         29.4               58.7
maxdep          207             1.97     88.2         29.4               58.7

In [4]:
df_lifetime['h2_loss_delta'] = df_lifetime['h2_loss']-df_lifetime.loc['CNTR']['h2_loss']
df_lifetime['h2_atm_loss_delta'] = df_lifetime['h2_atm_loss']-df_lifetime.loc['CNTR']['h2_atm_loss']
df_lifetime['h2_soil_sink_loss_delta'] = df_lifetime['h2_soil_sink_loss']-df_lifetime.loc['CNTR']['h2_soil_sink_loss']
df_lifetime

,h2_burden,h2_burden_delta,h2_loss,h2_atm_loss,h2_soil_sink_loss,h2_loss_delta,h2_atm_loss_delta,h2_soil_sink_loss_delta
CNTR,205,0.00,87.2,29.2,58.0,0.00,0.00,0.00
antro01,205,0.22,87.3,29.2,58.1,0.10,0.03,0.07
antro1,207,2.15,88.2,29.5,58.7,0.99,0.30,0.69
antro10,226,21.5,97.1,32.1,65.0,9.90,2.96,6.94
antro100,423,218,186,58.0,128,99.1,28.9,70.2
nemo,207,2.53,88.2,29.5,58.7,0.99,0.33,0.66
epia,207,1.93,88.2,29.4,58.7,0.99,0.27,0.73
munich,207,2.05,88.2,29.5,58.7,0.99,0.28,0.70
usdrydep,206,1.76,88.2,29.4,58.8,0.99,0.24,0.75
maud,207,2.56,88.2,29.5,58.7,0.99,0.33,0.66
zep,207,2.07,88.2,29.4,58.7,0.99,0.28,0.71
maxdep,207,1.97,88.2,29.4,58.7,0.99,0.27,0.72

In [5]:
df_lifetime_ssp = pd.read_csv(outputpath + 'for_lifetimetable_ssp.csv',sep=',',index_col=0)
df_lifetime_ssp

,h2_burden,h2_burden_delta,h2_loss,h2_atm_loss,h2_soil_sink_loss
10CH4_SSP119,188,7.15,78.6,25.2,53.4
10CH4_SSP434,235,9.96,94.8,28.6,66.1
10CH4_SSP585,245,11.1,100,31.4,68.9
CNTR_SSP119,181,0.00,76.4,24.9,51.5
CNTR_SSP434,225,0.00,91.8,28.3,63.5
CNTR_SSP585,234,0.00,97.0,31.0,66.0
antro10_SSP119,203,21.8,86.4,27.8,58.5
antro10_SSP434,247,22.4,102,31.0,70.7
antro10_SSP585,256,22.0,107,33.8,73.0

In [6]:
ssps = ['SSP119','SSP434','SSP585']
df_lifetime_ssp['h2_loss_delta']=np.nan
df_lifetime_ssp['h2_atm_loss_delta']=np.nan
df_lifetime_ssp['h2_soil_sink_loss_delta']=np.nan


for ssp in ssps:
    name = 'antro10_'+ssp
    df_lifetime_ssp.loc[name,'h2_loss_delta'] = df_lifetime_ssp.loc[name]['h2_loss']-df_lifetime_ssp.loc['CNTR_'+ssp]['h2_loss']
    df_lifetime_ssp.loc[name,'h2_atm_loss_delta'] = df_lifetime_ssp.loc[name]['h2_atm_loss']-df_lifetime_ssp.loc['CNTR_'+ssp]['h2_atm_loss']
    df_lifetime_ssp.loc[name,'h2_soil_sink_loss_delta'] = df_lifetime_ssp.loc[name]['h2_soil_sink_loss']-df_lifetime_ssp.loc['CNTR_'+ssp]['h2_soil_sink_loss']

df_lifetime_ssp

,h2_burden,h2_burden_delta,h2_loss,h2_atm_loss,h2_soil_sink_loss,h2_loss_delta,h2_atm_loss_delta,h2_soil_sink_loss_delta
10CH4_SSP119,188,7.15,78.6,25.2,53.4,NaN,NaN,NaN
10CH4_SSP434,235,9.96,94.8,28.6,66.1,NaN,NaN,NaN
10CH4_SSP585,245,11.1,100,31.4,68.9,NaN,NaN,NaN
CNTR_SSP119,181,0.00,76.4,24.9,51.5,NaN,NaN,NaN
CNTR_SSP434,225,0.00,91.8,28.3,63.5,NaN,NaN,NaN
CNTR_SSP585,234,0.00,97.0,31.0,66.0,NaN,NaN,NaN
antro10_SSP119,203,21.8,86.4,27.8,58.5,9.90,2.88,7.03
antro10_SSP434,247,22.4,102,31.0,70.7,9.90,2.71,7.19
antro10_SSP585,256,22.0,107,33.8,73.0,9.89,2.82,7.07

Lifetime and perturbation lifetime table

In [7]:
columns = ['H2 total lifetime [yrs]', 
           'H2 perturbation lifetime [yrs]', 
           'delta tot [yrs]',
           'delta tot [%]',
           'H2 atm lifetime [yrs]', 
           'H2 atm. perturbation lifetime [yrs]', 
           'delta atm [yrs]',
           'delta atm [%]',
           'H2 drydep lifetime [yrs]', 
           'H2 drydep perturbation lifetime [yrs]',
           'delta drydep [yrs]',
           'delta drydep [%]']

df_index = np.concatenate((df_lifetime.index.values ,ssps))

table_lifetime = pd.DataFrame([],index=df_index,columns=columns)

In [8]:
lifetime = df_lifetime.loc['CNTR']['h2_burden']/df_lifetime.loc['CNTR']['h2_loss']
atm_lifetime = df_lifetime.loc['CNTR']['h2_burden']/df_lifetime.loc['CNTR']['h2_atm_loss']
soil_sink_lifetime = df_lifetime.loc['CNTR']['h2_burden']/df_lifetime.loc['CNTR']['h2_soil_sink_loss']

for name in df_lifetime.drop('CNTR').index:
    table_lifetime.loc[name,'H2 total lifetime [yrs]'] = lifetime
    table_lifetime.loc[name,'H2 atm lifetime [yrs]'] = atm_lifetime    
    table_lifetime.loc[name,'H2 drydep lifetime [yrs]'] = soil_sink_lifetime


    table_lifetime.loc[name,'H2 perturbation lifetime [yrs]'] = df_lifetime.loc[name]['h2_burden_delta']/df_lifetime.loc[name]['h2_loss_delta']
    table_lifetime.loc[name,'H2 atm. perturbation lifetime [yrs]'] = df_lifetime.loc[name]['h2_burden_delta']/df_lifetime.loc[name]['h2_atm_loss_delta']
    table_lifetime.loc[name,'H2 drydep perturbation lifetime [yrs]'] =  df_lifetime.loc[name]['h2_burden_delta']/df_lifetime.loc[name]['h2_soil_sink_loss_delta']

for name in ssps:
    table_lifetime.loc[name,'H2 total lifetime [yrs]'] = df_lifetime_ssp.loc['CNTR_'+name]['h2_burden']/df_lifetime_ssp.loc['CNTR_'+name]['h2_loss']
    table_lifetime.loc[name,'H2 atm lifetime [yrs]'] = df_lifetime_ssp.loc['CNTR_'+name]['h2_burden']/df_lifetime_ssp.loc['CNTR_'+name]['h2_atm_loss']  
    table_lifetime.loc[name,'H2 drydep lifetime [yrs]'] = df_lifetime_ssp.loc['CNTR_'+name]['h2_burden']/df_lifetime_ssp.loc['CNTR_'+name]['h2_soil_sink_loss']


    table_lifetime.loc[name,'H2 perturbation lifetime [yrs]'] = df_lifetime_ssp.loc['antro10_'+name]['h2_burden_delta']/df_lifetime_ssp.loc['antro10_'+name]['h2_loss_delta']
    table_lifetime.loc[name,'H2 atm. perturbation lifetime [yrs]'] = df_lifetime_ssp.loc['antro10_'+name]['h2_burden_delta']/df_lifetime_ssp.loc['antro10_'+name]['h2_atm_loss_delta']
    table_lifetime.loc[name,'H2 drydep perturbation lifetime [yrs]'] =  df_lifetime_ssp.loc['antro10_'+name]['h2_burden_delta']/df_lifetime_ssp.loc['antro10_'+name]['h2_soil_sink_loss_delta']


table_lifetime['delta tot [%]']=100.0*(table_lifetime['H2 perturbation lifetime [yrs]']-table_lifetime['H2 total lifetime [yrs]'])/table_lifetime['H2 total lifetime [yrs]']
table_lifetime['delta atm [%]']=100.0*(table_lifetime['H2 atm. perturbation lifetime [yrs]']-table_lifetime['H2 atm lifetime [yrs]'])/table_lifetime['H2 atm lifetime [yrs]']
table_lifetime['delta drydep [%]']=100.0*(table_lifetime['H2 drydep perturbation lifetime [yrs]']-table_lifetime['H2 drydep lifetime [yrs]'])/table_lifetime['H2 drydep lifetime [yrs]']


table_lifetime['delta tot [yrs]'] = table_lifetime['H2 perturbation lifetime [yrs]']  - table_lifetime['H2 total lifetime [yrs]'] 
table_lifetime['delta atm [yrs]'] = table_lifetime['H2 atm. perturbation lifetime [yrs]']  - table_lifetime['H2 atm lifetime [yrs]'] 
table_lifetime['delta drydep [yrs]'] = table_lifetime['H2 drydep perturbation lifetime [yrs]']  - table_lifetime['H2 drydep lifetime [yrs]'] 
table_lifetime

,H2 total lifetime [yrs],H2 perturbation lifetime [yrs],delta tot [yrs],delta tot [%],H2 atm lifetime [yrs],H2 atm. perturbation lifetime [yrs],delta atm [yrs],delta atm [%],H2 drydep lifetime [yrs],H2 drydep perturbation lifetime [yrs],delta drydep [yrs],delta drydep [%]
CNTR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
antro01,2.35,2.17,-0.18,-7.53,7.02,7.23,0.22,3.12,3.53,3.10,-0.43,-12.1
antro1,2.35,2.17,-0.18,-7.52,7.02,7.24,0.22,3.18,3.53,3.10,-0.43,-12.1
antro10,2.35,2.17,-0.17,-7.40,7.02,7.27,0.25,3.59,3.53,3.10,-0.43,-12.1
antro100,2.35,2.20,-0.15,-6.27,7.02,7.55,0.53,7.57,3.53,3.10,-0.42,-12.0
nemo,2.35,2.56,0.21,9.04,7.02,7.64,0.62,8.85,3.53,3.85,0.32,9.13
epia,2.35,1.94,-0.40,-17.2,7.02,7.25,0.23,3.31,3.53,2.66,-0.87,-24.7
munich,2.35,2.08,-0.27,-11.3,7.02,7.24,0.22,3.18,3.53,2.92,-0.61,-17.2
usdrydep,2.35,1.77,-0.57,-24.5,7.02,7.18,0.16,2.31,3.53,2.35,-1.17,-33.3
maud,2.35,2.59,0.24,10.2,7.02,7.73,0.71,10.2,3.53,3.89,0.36,10.2
zep,2.35,2.09,-0.26,-11.0,7.02,7.40,0.38,5.47,3.53,2.91,-0.62,-17.4
maxdep,2.35,1.99,-0.35,-15.0,7.02,7.22,0.21,2.94,3.53,2.75,-0.77,-21.9
SSP119,2.37,2.20,-0.16,-6.93,7.26,7.59,0.33,4.56,3.51,3.11,-0.41,-11.6
SSP434,2.45,2.26,-0.19,-7.78,7.95,8.26,0.31,3.87,3.54,3.11,-0.43,-12.2
SSP585,2.41,2.22,-0.19,-7.99,7.55,7.80,0.25,3.27,3.55,3.11,-0.44,-12.5

In [9]:
table_to_manuscript = table_lifetime.drop('CNTR')
table_to_manuscript.index = [sub.replace('antro', 'anthro') for sub in table_to_manuscript.index]
table_to_manuscript.index = [sub.replace('maxdep', 'lowlatdep') for sub in table_to_manuscript.index]
table_to_manuscript = table_to_manuscript.drop(['delta tot [yrs]','delta atm [yrs]','delta drydep [yrs]'],axis=1)
table_to_manuscript

,H2 total lifetime [yrs],H2 perturbation lifetime [yrs],delta tot [%],H2 atm lifetime [yrs],H2 atm. perturbation lifetime [yrs],delta atm [%],H2 drydep lifetime [yrs],H2 drydep perturbation lifetime [yrs],delta drydep [%]
anthro01,2.35,2.17,-7.53,7.02,7.23,3.12,3.53,3.10,-12.1
anthro1,2.35,2.17,-7.52,7.02,7.24,3.18,3.53,3.10,-12.1
anthro10,2.35,2.17,-7.40,7.02,7.27,3.59,3.53,3.10,-12.1
anthro100,2.35,2.20,-6.27,7.02,7.55,7.57,3.53,3.10,-12.0
nemo,2.35,2.56,9.04,7.02,7.64,8.85,3.53,3.85,9.13
epia,2.35,1.94,-17.2,7.02,7.25,3.31,3.53,2.66,-24.7
munich,2.35,2.08,-11.3,7.02,7.24,3.18,3.53,2.92,-17.2
usdrydep,2.35,1.77,-24.5,7.02,7.18,2.31,3.53,2.35,-33.3
maud,2.35,2.59,10.2,7.02,7.73,10.2,3.53,3.89,10.2
zep,2.35,2.09,-11.0,7.02,7.40,5.47,3.53,2.91,-17.4
lowlatdep,2.35,1.99,-15.0,7.02,7.22,2.94,3.53,2.75,-21.9
SSP119,2.37,2.20,-6.93,7.26,7.59,4.56,3.51,3.11,-11.6
SSP434,2.45,2.26,-7.78,7.95,8.26,3.87,3.54,3.11,-12.2
SSP585,2.41,2.22,-7.99,7.55,7.80,3.27,3.55,3.11,-12.5